services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yugi2017
      MYSQL_DATABASE: HospitalDB

    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mysql_data: